-- MySQL Script generated by MySQL Workbench
-- Thu Jul 16 13:57:59 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuario` ;

CREATE TABLE IF NOT EXISTS `usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `tipo` ENUM('aluno', 'professor', 'admin') NOT NULL DEFAULT 'aluno',
  `status` ENUM('ativo', 'bloqueado') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categoria` ;

CREATE TABLE IF NOT EXISTS `categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `category_id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`nome` ASC)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `livros` ;

CREATE TABLE IF NOT EXISTS `livros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoria_id` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `autor` VARCHAR(45) NOT NULL,
  `ano_publicacao` INT NOT NULL,
  `quantidade_total` INT NOT NULL DEFAULT 0,
  `quantidade_disponivel` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `categoria_id_idx` (`categoria_id` ASC),
  UNIQUE INDEX `livro_id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_livros_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `categoria` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emprestimos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `emprestimos` ;

CREATE TABLE IF NOT EXISTS `emprestimos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `data_retirada` DATE NOT NULL,
  `data_devolucao_prevista` DATE NOT NULL,
  `data_devolucao_real` DATE NULL,
  `status` ENUM('ativo', 'devolvido', 'atrasado') NOT NULL DEFAULT 'ativo',
  PRIMARY KEY (`id`),
  INDEX `usuario_id_idx` (`usuario_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_emprestimos_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `itens` ;

CREATE TABLE IF NOT EXISTS `itens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `emprestimo_id` INT NOT NULL,
  `livro_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `emprestimo_id_idx` (`emprestimo_id` ASC),
  INDEX `livro_id_idx` (`livro_id` ASC),
  UNIQUE INDEX `itens_id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_itens_emprestimos`
    FOREIGN KEY (`emprestimo_id`)
    REFERENCES `emprestimos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_itens_livros`
    FOREIGN KEY (`livro_id`)
    REFERENCES `livros` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `penalidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `penalidades` ;

CREATE TABLE IF NOT EXISTS `penalidades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `emprestimo_id` INT NOT NULL,
  `status` ENUM('paga', 'pendente') NOT NULL DEFAULT 'pendente',
  `valor_multa` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `penalidades_id_UNIQUE` (`id` ASC),
  INDEX `usuario_id_idx` (`usuario_id` ASC),
  INDEX `emprestimo_id_idx` (`emprestimo_id` ASC),
  CONSTRAINT `fk_penalidades_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_penalidades_emprestimos`
    FOREIGN KEY (`emprestimo_id`)
    REFERENCES `emprestimos` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;